// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantManagementSystem.Database;

namespace RestaurantManagementSystem.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200213082236_I")]
    partial class I
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Admin.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealHourId")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("FoodItemId");

                    b.HasIndex("MealHourId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Admin.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IngredientName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Admin.Models.MealHour", b =>
                {
                    b.Property<int>("MealHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MealHourTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MealHourId");

                    b.ToTable("MealHour");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Admin.Models.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Coupon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidatyStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidatyTo")
                        .HasColumnType("datetime2");

                    b.HasKey("OfferId");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Admin.Models.RequiredMaterial", b =>
                {
                    b.Property<int>("RequiredMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInGram")
                        .HasColumnType("int");

                    b.HasKey("RequiredMaterialId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RequiredMaterial");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Admin.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BookedStatus")
                        .HasColumnType("bit");

                    b.Property<int>("BookingPrice")
                        .HasColumnType("int");

                    b.Property<int>("TableCapacity")
                        .HasColumnType("int");

                    b.Property<string>("TableNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableId");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Customer.Models.Customers", b =>
                {
                    b.Property<int>("CustomersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomersName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomersId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Manager.Models.CustomerOrderDetails", b =>
                {
                    b.Property<int>("CustomerOrderDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerOrderedTableId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int>("FoodItemNo")
                        .HasColumnType("int");

                    b.Property<int?>("OfferId")
                        .HasColumnType("int");

                    b.Property<bool>("OnlineStatus")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CustomerOrderDetailsId");

                    b.HasIndex("CustomerOrderedTableId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("OfferId");

                    b.ToTable("CustomerOrderDetails");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Manager.Models.CustomerOrderedTable", b =>
                {
                    b.Property<int>("CustomerOrderedTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookTimeFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BookTimeTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ConfirmStatus")
                        .HasColumnType("bit");

                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("CustomerOrderedTableId");

                    b.HasIndex("CustomersId");

                    b.HasIndex("TableId");

                    b.ToTable("CustomerOrderedTable");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.StockManager.Models.StockDetails", b =>
                {
                    b.Property<int>("StockDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AvailableStock")
                        .HasColumnType("datetime2");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("StockInDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StockDetailsId");

                    b.HasIndex("IngredientId");

                    b.ToTable("StockDetails");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Admin.Models.FoodItem", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Areas.Admin.Models.MealHour", "MealHour")
                        .WithMany()
                        .HasForeignKey("MealHourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Admin.Models.RequiredMaterial", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Areas.Admin.Models.FoodItem", "FoodItem")
                        .WithMany("RequiredMaterials")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagementSystem.Areas.Admin.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Manager.Models.CustomerOrderDetails", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Areas.Manager.Models.CustomerOrderedTable", "CustomerOrderedTable")
                        .WithMany()
                        .HasForeignKey("CustomerOrderedTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagementSystem.Areas.Admin.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId");

                    b.HasOne("RestaurantManagementSystem.Areas.Admin.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId");
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.Manager.Models.CustomerOrderedTable", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Areas.Customer.Models.Customers", "Customers")
                        .WithMany("CustomerOrderedTables")
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantManagementSystem.Areas.Admin.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RestaurantManagementSystem.Areas.StockManager.Models.StockDetails", b =>
                {
                    b.HasOne("RestaurantManagementSystem.Areas.Admin.Models.Ingredient", "Ingredient")
                        .WithMany("StockDetails")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
